### PR TITLE
Fix CI build broken by Max Market Share calling a nonexistent API

### PR DESCRIPTION
**Pull request by Trawis**
## Summary
- Every CI run on `develop` (and every open PR built against it) has been failing since #119 with `error CS1061: 'SoftwareProduct' does not contain a definition for 'MarketShare'`. This restores a green build.

## Changes
- #119 removed the `#if SWINCBETA1_7 || SWINCBETA1_8 || SWINCBETA1_9 || SWINCBETA1_10` guard around the Max Market Share button/toggle, on the claim that the vendored `Assembly-CSharp.dll` exposes `SoftwareProduct.MarketShare` unconditionally. That claim was wrong: I inspected the vendored assembly's .NET metadata directly (no `dotnet`/decompiler available in this environment, so I parsed the PE/CLI metadata tables with `dnfile` in Python) and confirmed `SoftwareProduct` has no `MarketShare` field, property, or method under any name, and `MarketSimulation` has no method to directly assign a product's share either. The only real `MarketShare` in this build is on `DistributionPlatform` (`company.Distribution.MarketShare`, a different, company-level concept already used correctly by `DigitalDistributionMonopol`).
- Removed the Max Market Share button, the Auto Max Market Share toggle, their settings default, UI wiring, and localization strings (all 7 languages), rather than guessing at a replacement API — per this repo's "verify before implementing" pattern for native game hooks. Filed #150 to track a proper reimplementation once a real mechanism is verified.
- Updated `FEATURES.md`, `docs/project/architecture.md`, and `CHANGELOG.md` to match.

## Requirements / Spec Alignment
- [x] Acceptance criteria / issue / ticket reviewed if provided (n/a — CI break, no linked issue; follow-up tracked as #150)
- [x] Conflicts or unclear requirements reported (n/a)
- [ ] FSD reviewed if provided (n/a, none referenced)
- [ ] TSD reviewed if provided (n/a, none referenced)
- [ ] GDD reviewed if game-related and provided (n/a, none referenced)

## Documentation
- [x] README.md updated if needed (n/a, no README claims involved)
- [x] CHANGELOG.md updated if needed
- [x] FEATURES.md updated if needed
- [x] docs/ updated if needed (architecture.md)
- [x] No invented features, claims, screenshots, benchmarks, or compatibility guarantees

## Validation
- [ ] Build ran or skip reason documented — **`dotnet` is not installed in this environment**, so `dotnet build` could not be run. Instead: parsed the vendored assembly's real CLI metadata (fields/properties/methods) with `dnfile` to confirm `SoftwareProduct.MarketShare` does not exist anywhere in the type (root cause of the CI failure) and that no alternative member exists to swap in; manually verified brace balance and re-checked every remaining reference to the removed setting/method across source, docs, and all localization files.
- [ ] Format/lint checks ran where configured — same reason, `dotnet format` unavailable.
- [x] Implementation rechecked against task/specs/changed files
- [ ] Unit tests added/updated where feasible — no test project exists in the repo for this behavior
- [ ] Tests ran or skip reason documented — see above
- [x] Smoke/manual check ran where practical — not applicable to a pure removal; confirmed no dangling references remain via full-repo grep

## Branching / Merge Safety
- [x] Work was done on a task branch
- [ ] Branch name follows `feature/<short-kebab-description>`, `release/<version>`, or `hotfix/<short-kebab-description>` — this branch (`claude/fox-cicd-ikc3d0`) was assigned by the session harness rather than named by hand; flagging so a maintainer can rename/recreate it under Git Flow convention if that matters here
- [x] Branch family follows strict Git Flow in intent (based on `develop`, targets `develop`)
- [x] PR targets the correct Git Flow branch (`develop`)
- [x] No auto-merge requested/performed
- [x] No branch protection bypass requested/performed

## Notes / Risks
- This is a pure removal of a broken feature, not a reimplementation. Anyone with the Auto Max Market Share toggle enabled in an existing save will simply have that (already-nonfunctional-in-this-build) setting ignored on load, per the existing "log unregistered setting keys" behavior (#146) — no save-compatibility risk.
- Follow-up tracked in #150.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_016BD3q2y2jwDch2U3Tf57xy

---
_Generated by [Claude Code](https://claude.ai/code/session_016BD3q2y2jwDch2U3Tf57xy)_

### CODE REVIEW

**Comment by Trawis** [comment]
Closing in favor of #152 — same fix, moved to a branch (`feature/fix-market-share-ci-build`) that follows this repo's `feature/<short-kebab-description>` Git Flow naming convention instead of the session-assigned `claude/fox-cicd-ikc3d0`.


---
_Generated by [Claude Code](https://claude.ai/code)_
